### ISSUE TITLE
libprotobuf ERROR

### ISSUE THREAD

**Issue by HilmiK** [thuml/MADA#1]
When I try to run on my precompiled caffe, I got the following error:

[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 559:25: Message type "caffe.LayerParameter" has no field named "gradient_scalar_param".
F0429 12:54:53.980785 23869 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./models/mada/train_val.prototxt

Should I recompile the caffe ?
Thanks

**Comment by HilmiK** [comment]
I recompiled caffe and problem solved.

**Comment by vipulbjj** [comment]
@HilmiK Can you please tell how did you compile caffe?
I'm getting an error while doing 'make all'.
